{
 "title": "GoShimmer Local Metrics",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(iota_info_app, instance)"
    }
   },
   {
    "name": "NodeID",
    "label": "Node Identity",
    "query": {
     "query": "label_values(iota_info_app, nodeID)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GoShimmer",
   "type": "stat",
   "description": "Version number of node software.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_info_app{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node Identity",
   "type": "stat",
   "description": "Shortened version of the public key of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_info_app{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows the time elapsed since the start of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "description": "Describes if the node is in synced state.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangleTimeSynced{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total MPS",
   "type": "stat",
   "description": "Aggregated MPS for all message types in the communication layer.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(tangle_messages_per_component_count{component=\"Store\",instance=\"$instance\"}[5m])",
     "legendFormat": "Total MPS"
    }
   ]
  },
  {
   "title": "Access Mana (Current)",
   "type": "stat",
   "description": "Amount of access mana this node has",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si: m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mana_access{instance=\"$instance\",nodeID=\"$NodeID\"}"
    }
   ]
  },
  {
   "title": "Consensus Mana (Current)",
   "type": "stat",
   "description": "Amount of consensus mana this node has.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si: m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mana_consensus{instance=\"$instance\",nodeID=\"$NodeID\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Current CPU usage of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_size_bytes{instance=\"$instance\"}/1024/1024"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "stat",
   "description": "Memory consumed by the node.",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_mem_usage_bytes{instance=\"$instance\"}/1024/1024"
    }
   ]
  },
  {
   "title": "MPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Message Per Second Per Type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "MPS" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_messages_per_type_count{instance=\"$instance\"}[5m])",
     "legendFormat": "Message Per Second {{message_type}}"
    }
   ]
  },
  {
   "title": "Message Per Second Per Component",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "MPS" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_messages_per_component_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{component}} MPS"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "graph",
   "description": "Shows tips in message and value layer.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_tips_count{instance=\"$instance\"}",
     "legendFormat": "Message Layer Tips"
    }
   ]
  },
  {
   "title": "Autopeering Neighbor Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Distance" }
   ],
   "targets": [
    {
     "expr": "autopeering_avg_distance{instance=\"$instance\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "autopeering_max_distance{instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "autopeering_min_distance{instance=\"$instance\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Current Neighbors",
   "type": "stat",
   "description": "Number of currently connected neighbors.",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_connections_count{instance=\"$instance\"} - autopeering_neighbor_drop_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "AvgNeighbor Connection Lifetime",
   "type": "stat",
   "description": "Calculated for each dropped neighbor.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_avg_neighbor_connection_lifetime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "New Neighbor Connections",
   "type": "stat",
   "description": "Amount of newly registered neighbor connections.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_connections_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dropped Neighbor Connections",
   "type": "stat",
   "description": "Amount of neighbor connections dropped.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_drop_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solidifier-requested messages per second",
   "type": "graph",
   "description": "Number of messages requested through solidification. ",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_message_solidification_missing_message_count{instance=\"$instance\"}[5m])",
     "legendFormat": "Solidifier-requested messages"
    }
   ]
  },
  {
   "title": "Solidifier-requested messages total",
   "type": "graph",
   "description": "Number of messages requested through solidification. ",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_solidification_missing_message_count{instance=\"$instance\"}",
     "legendFormat": "Solidifier-requested messages"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "process_mem_usage_bytes{instance=\"$instance\"}/1024/1024",
     "legendFormat": "Memory Consumption"
    }
   ]
  },
  {
   "title": "Missing Messages",
   "type": "graph",
   "description": "Number of messages in missingMessageStore. These are the message the node knows it doesn't have and tries to requests them.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_missing_count_db{instance=\"$instance\"}",
     "legendFormat": "Missing Messages"
    }
   ]
  },
  {
   "title": "Messages in Database",
   "type": "graph",
   "description": "Describes the amount of total, solid and not solid messages in the node's database.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_messages_per_component_count{component=\"Solidifier\",instance=\"$instance\"}",
     "legendFormat": "Solid Messages in DB"
    },
    {
     "expr": "tangle_messages_per_component_count{component=\"Store\",instance=\"$instance\"} - tangle_messages_per_component_count{component=\"Solidifier\",instance=\"$instance\"}",
     "legendFormat": "Not Solid Messages in DB"
    },
    {
     "expr": "tangle_messages_per_component_count{component=\"Store\",instance=\"$instance\"}",
     "legendFormat": "Total Messages in DB"
    }
   ]
  },
  {
   "title": "Message Request Queue Size",
   "type": "graph",
   "description": "Number of messages currently requested by the message tangle.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_request_queue_size{instance=\"$instance\"}",
     "legendFormat": "Message Request Queue Size"
    }
   ]
  },
  {
   "title": "Average Solidification Time",
   "type": "timeseries",
   "description": "Average time it takes to solidify messages.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(tangle_message_total_time_since_received{component=\"Scheduler\",instance=\"$instance\"}[1m])/rate(tangle_messages_per_component_count{component=\"Scheduler\",instance=\"$instance\"}[1m])",
     "legendFormat": "Scheduler time"
    },
    {
     "expr": "sum(rate(tangle_message_total_scheduling_time{instance=\"$instance\"}[1m]))/sum(rate(tangle_messages_per_component_count{component=\"Scheduler\",instance=\"$instance\"}[1m]))",
     "legendFormat": "Scheduling only"
    },
    {
     "expr": "rate(tangle_message_total_time_since_received{component=\"Booker\",instance=\"$instance\"}[1m])/rate(tangle_messages_per_component_count{component=\"Booker\",instance=\"$instance\"}[1m])",
     "legendFormat": "Booker time"
    },
    {
     "expr": "rate(tangle_scheduler_tick_total_time{instance=\"$instance\"}[1m])/rate(tangle_scheduler_tick_count{instance=\"$instance\"}[1m])",
     "legendFormat": "Scheduler tick time"
    },
    {
     "expr": "rate(tangle_message_processed_trigger_time{instance=\"$instance\"}[1m])/rate(tangle_message_processed_trigger_count{instance=\"$instance\"}[1m])",
     "legendFormat": "Trigger process time"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(traffic_analysis_outbound_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "Analysis TX"
    },
    {
     "expr": "irate(traffic_autopeering_inbound_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "Autopeering RX"
    },
    {
     "expr": "irate(traffic_autopeering_outbound_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "Autopeering TX"
    },
    {
     "expr": "irate(traffic_fpc_inbound_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "FPC RX"
    },
    {
     "expr": "irate(traffic_fpc_outbound_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "FPC TX"
    },
    {
     "expr": "irate(traffic_gossip_inbound_packets{instance=\"$instance\"}[1m])",
     "legendFormat": "Gossip RX"
    },
    {
     "expr": "irate(traffic_gossip_outbound_packets{instance=\"$instance\"}[1m])",
     "legendFormat": "Gossip Tx"
    }
   ]
  },
  {
   "title": "Analysis",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_analysis_outbound_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Gossip TX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_gossip_outbound_packets{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Gossip RX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_gossip_inbound_packets{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Autopeering TX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_autopeering_outbound_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Autopeering RX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_autopeering_inbound_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Mana",
     "type": "stat",
     "description": "Amount of access mana this node has",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_access{instance=\"$instance\",nodeID=\"$NodeID\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Mana Percentile",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_access_percentile{instance=\"$instance\"}",
       "legendFormat": "Access"
      },
      {
       "expr": "mana_consensus_percentile{instance=\"$instance\"}",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Average Mana",
     "type": "stat",
     "description": "Average mana of a node i nthe network.",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(mana_access{instance=\"$instance\"})",
       "legendFormat": "Access"
      },
      {
       "expr": "avg(mana_consensus{instance=\"$instance\"})",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Standard Deviation of Mana",
     "type": "stat",
     "description": "Standard deviation of mana of nodes in the network.",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev(mana_access{instance=\"$instance\"})",
       "legendFormat": "Access"
      },
      {
       "expr": "stddev(mana_consensus{instance=\"$instance\"})",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Average neighbours mana",
     "type": "stat",
     "description": "Average access and consensus mana of a nodes nneighbours.",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_average_neighbors_access{instance=\"$instance\"}",
       "legendFormat": "Access"
      },
      {
       "expr": "mana_average_neighbors_consensus{instance=\"$instance\"}",
       "legendFormat": "Consensus"
      }
     ]
    },
    {
     "title": "Total Mana",
     "type": "graph",
     "description": "Total Access & Consensus Mana In the network.",
     "gridPos": { "h": 15, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "sum(mana_access{instance=\"$instance\"})",
       "legendFormat": "Total Access Mana In Network"
      },
      {
       "expr": "sum(mana_consensus{instance=\"$instance\"})",
       "legendFormat": "Total Consensus Mana In Network"
      }
     ]
    },
    {
     "title": "Access Mana Distribution In Network",
     "type": "graph",
     "description": "Histogram of access mana of nodes.",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Number of Nodes" }
     ],
     "targets": [
      {
       "expr": "mana_access{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Consensus Mana Distribution in Network",
     "type": "graph",
     "description": "Histogram of consensus mana of nodes.",
     "gridPos": { "h": 12, "w": 9, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Number of Nodes" }
     ],
     "targets": [
      {
       "expr": "mana_consensus{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Access Mana",
     "type": "graph",
     "description": "Amount of access mana this node has",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_access{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Network Wide Access Mana",
     "type": "graph",
     "description": "Amount of access mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_access{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Access Mana Allocation",
     "type": "piechart",
     "description": "Allocation of access mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_access{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Consensus Mana",
     "type": "graph",
     "description": "Amount of consensus mana this node has.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_consensus{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Network Wide Consensus Mana",
     "type": "graph",
     "description": "Amount of consensus mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_consensus{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Consensus Mana Allocation",
     "type": "piechart",
     "description": "Allocation of consensus mana of nodes in the network.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mana_consensus{instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Mana Percentile Development",
     "type": "graph",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "mana_access_percentile{instance=\"$instance\"}",
       "legendFormat": "Access Percentile"
      },
      {
       "expr": "mana_consensus_percentile{instance=\"$instance\"}",
       "legendFormat": "Consensus Percentile"
      }
     ]
    },
    {
     "title": "Average Pledged Access Mana",
     "type": "graph",
     "description": "Average pledged BM1 and BM2 of access mana pledged to the node",
     "gridPos": { "h": 11, "w": 7, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_average_access_pledge{type=\"bm2\",instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Average Pledged Access Mana",
     "type": "graph",
     "description": "Average pledged BM1 and BM2 of access mana pledged to the node",
     "gridPos": { "h": 11, "w": 7, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_average_access_pledge{type=\"bm2\",instance=\"$instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Mana Delegated To Node",
     "type": "graph",
     "description": "Amount of mana currently delegated to the node.",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "si: m" } },
     "yaxes": [
      { "format": "si: m" }
     ],
     "targets": [
      {
       "expr": "mana_delegated_amount{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "OTV metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Message finalization time",
   "type": "graph",
   "description": "Indicates an average time it takes for a message to be finalized since it is received by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_message_finalization_time_since_received{instance=\"$instance\"}[1m]) / irate(tangle_message_finalized_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{messageType}} avg. finalization time"
    }
   ]
  },
  {
   "title": "Branch finalization time",
   "type": "graph",
   "description": "Indicates an average time it takes for a message to be finalized since it is received by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_branch_confirmation_time{instance=\"$instance\"}[30s]) / rate(tangle_branch_confirmed_count{instance=\"$instance\"}[30s])",
     "legendFormat": "Average branch confirmation time"
    }
   ]
  },
  {
   "title": "Average number of parents by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tangle_messages_parent_count_per_type{instance=\"$instance\"}[1m])) by (type,instance) / on(instance) group_left() sum(irate(tangle_message_finalized_count{instance=\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total number of branches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_branch_total_count_db{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of unresolved branches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_branch_total_count_db{instance=\"$instance\"} - tangle_branch_finalized_count_db{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of finalized branches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_branch_finalized_count_db{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of confirmed branches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_branch_confirmed_count{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Scheduler metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Mana-scaled queue size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (node_id) (scheduler_buffer_size_per_node{instance=\"$instance\"}/scheduler_amana_per_node{instance=\"$instance\"}))",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Scheduling rate",
   "type": "stat",
   "description": "Rate at which scheduler processes messages from the buffer",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_rate{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Scheduled messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_messages_per_component_count{component=\"Scheduler\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Skipped messages",
   "type": "stat",
   "description": "Messages skipped by the scheduler, because they were confirmed before. ",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_messages_per_component_count{component=\"SchedulerSkipped\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max buffer size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_max_size{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dropped messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tangle_messages_per_component_count{component=\"SchedulerDropped\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "All messages count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_total_msg_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (node_id) (scheduler_buffer_size_per_node{instance=\"$instance\"}))",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Current buffer size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_total_size{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unready messages count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_total_msg_count{instance=\"$instance\"} - scheduler_buffer_ready_msg_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ready messages count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_buffer_ready_msg_count{instance=\"$instance\"}"
    }
   ]
  }
 ]
}